### ISSUE TITLE
Getting ValueError while running through the code

### ISSUE THREAD

**Issue by Jeetkarsh** [abhishekkrthakur/bert-entity-extraction#1]
Following is the Traceback for your reference :

Traceback (most recent call last):
  File "train.py", line 102, in <module>
    train_loss = engine.train_fn(train_data_loader, model, optimizer, device, scheduler)
  File "/home/jeetkarshus/Notebooks/v1/Python_Scripts/src/engine.py", line 8, in train_fn
    for data in tqdm(data_loader, total=len(data_loader)):
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jeetkarshus/Notebooks/v1/Python_Scripts/src/dataset.py", line 27, in __getitem__
    add_special_tokens=False
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1425, in encode
    **kwargs,
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1737, in encode_plus
    **kwargs,
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 454, in _encode_plus
    first_ids = get_input_ids(text)
  File "/home/jeetkarshus/anaconda3/envs/NER/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 442, in get_input_ids
    f"Input {text} is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers."
ValueError: Input nan is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

I tried using smaller batch size but still the same issue.

**Comment by abhishekkrthakur** [comment]
Which dataset are you using?

**Comment by Jeetkarsh** [comment]
I am trying this on a Custom build datasets which include 4 different NER tags. I have ensured to keep the dateset in the same format as was used in this tutorial

**Comment by Jeetkarsh** [comment]
Thanks for your reply, Issue is it does train for some time but then stop working. I have properly checked for Nan values. So i suppose that's not a problem

  4%|██████▏                                                                                                                                                  | 14/343 [00:03<01:15,  4.33it/s]

**Comment by Jeetkarsh** [comment]
Just a gentle follow up. Did you got a chance to look into this. Thanks in advance.

**Comment by Jeetkarsh** [comment]
Issue was with the encoding. 

Updating to the correct encoding worked.

**Comment by stank2010** [comment]
I got the same point. What file that I should focus on?
