### ISSUE TITLE
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index']

### ISSUE THREAD

**Issue by sednaasil** [abhishekkrthakur/bert-entity-extraction#4]
Hi:

I am very new to using BERT and just followed along on your youtube.com video describing how to build and entity extraction workflow.  I downloaded the uncased_L-12_H-768_A-12 BERT model to use along with the tutorial; however, when I run the train.py script I get the following error: 
 
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index']

Would you be able to direct me on how to overcome?

v/r,
L

**Comment by zenithexpo** [comment]
Hey, I was also getting the same error, you can download the missing files from https://huggingface.co/bert-base-uncased/tree/main here.

**Comment by SudeshKumarSK** [comment]
I am getting an error while loading the pre-trained model. Can anybody help me out here?

Traceback (most recent call last):
  File "train.py", line 74, in <module>
    model = EntityModel(num_tag=num_tag, num_pos=num_pos)
  File "/Users/sk/dl/pos/abishek/src/model.py", line 24, in __init__
    self.bert = transformers.BertModel.from_pretrained(config.BASE_MODEL_PATH)
  File "/Users/sk/dl/pos/lib/python3.7/site-packages/transformers/modeling_utils.py", line 679, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "

Especially this error :
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
